# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: trusty

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/sklearn
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

matrix:
  include:
    python: 3.7
      env:
        - CHECK_WARNINGS="true"
        - CI_CPU_COUNT="3"
      if: type = cron OR commit_message =~ /\[scipy-dev\]/

    # As above but build scikit-learn with Intel C compiler (ICC).
    - python: 3.7
      env:
        - CHECK_WARNING="true"
        - BUILD_WITH_ICC="true"
        - CI_CPU_COUNT="3"
      if: type = cron OR commit_message =~ /\[icc-build\]/

    - python: 3.7
      env:
        - CI_CPU_COUNT="8"
      os: linux
      arch: arm64
      if: type = cron OR commit_message =~ /\[arm64\]/
  allow_failures:
    # allow_failures seems to be keyed on the python version
    # We are using this to allow failures for DISTRIB=scipy-dev-wheels
    - python: 3.5

install: source build_tools/travis/install.sh
script: bash build_tools/travis/test_script.sh
after_success: source build_tools/travis/after_success.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ffabb4df010b70cd624
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
